### ISSUE TITLE
Ajuste de tempo do slide

### ISSUE THREAD

**Issue by FillipeMagno** [tic-esteio/painel-slides#1]
Quais parâmetros devem ser alterados e em quais arquivos para manter as imagens por mais tempo antes da troca?

**Comment by somatorio** [comment]
está hardcoded, hahaha

https://github.com/tic-esteio/painel-slides/blob/61e74856cec29ebd1862ee95dd479de7c58ad714/slides.php#L53

**Comment by FillipeMagno** [comment]
Encontrei antes da resposta, ja ia colocar aqui, no arquivo responsiveslides.min, paramêtro timeout, tava com uma codificação estranha, "4e3", por isso não tinha mudado nele, vlw, agora to tentando escrever Última senha chamada e aumentar um pouco a fonte dela, se puder ajudar agradeço tbm.

**Comment by somatorio** [comment]
bah, pior que faz tanto tempo que não toco nisso que nem lembro mais... :(

**Comment by FillipeMagno** [comment]
Blz, de toda forma obrigado.
